// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Server.Data;

namespace Shop.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductSize", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("SizesId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "SizesId");

                    b.HasIndex("SizesId");

                    b.ToTable("ProductSize");

                    b.HasData(
                        new
                        {
                            ProductsId = 1,
                            SizesId = 2
                        },
                        new
                        {
                            ProductsId = 1,
                            SizesId = 3
                        },
                        new
                        {
                            ProductsId = 1,
                            SizesId = 4
                        },
                        new
                        {
                            ProductsId = 2,
                            SizesId = 2
                        },
                        new
                        {
                            ProductsId = 2,
                            SizesId = 3
                        },
                        new
                        {
                            ProductsId = 2,
                            SizesId = 4
                        },
                        new
                        {
                            ProductsId = 3,
                            SizesId = 1
                        },
                        new
                        {
                            ProductsId = 3,
                            SizesId = 2
                        },
                        new
                        {
                            ProductsId = 3,
                            SizesId = 3
                        },
                        new
                        {
                            ProductsId = 3,
                            SizesId = 4
                        },
                        new
                        {
                            ProductsId = 4,
                            SizesId = 8
                        },
                        new
                        {
                            ProductsId = 4,
                            SizesId = 9
                        },
                        new
                        {
                            ProductsId = 4,
                            SizesId = 10
                        },
                        new
                        {
                            ProductsId = 4,
                            SizesId = 11
                        });
                });

            modelBuilder.Entity("Shop.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "book",
                            Name = "Rukavice",
                            Url = "rukavice"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "camera-slr",
                            Name = "Kacige",
                            Url = "kacige"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "aperture",
                            Name = "Kostobrani",
                            Url = "kostobrani"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "book",
                            Name = "Kikovi",
                            Url = "kikovi"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "book",
                            Name = "Kimona",
                            Url = "kimona"
                        });
                });

            modelBuilder.Entity("Shop.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatuUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2022, 8, 16, 12, 46, 50, 228, DateTimeKind.Local).AddTicks(6687),
                            DatuUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rukavice za boks 10oz",
                            Image = "https://www.pride.hr/images/thumbs/0000925_4033-pride-pro-training-and-sparring-gloves_1000.jpeg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 19.99m,
                            Price = 9.99m,
                            Title = "Rukavice"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DateCreated = new DateTime(2022, 8, 16, 12, 46, 50, 231, DateTimeKind.Local).AddTicks(4034),
                            DatuUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rukavice marke Adidas 12oz",
                            Image = "https://www.pride.hr/images/thumbs/0001782_a7150-adidas-boxing-gloves-speed-50_1000.jpeg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 19.99m,
                            Price = 9.99m,
                            Title = "Rukavice Adidas"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DateCreated = new DateTime(2022, 8, 16, 12, 46, 50, 231, DateTimeKind.Local).AddTicks(4102),
                            DatuUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rukavice marke Adidas 14oz",
                            Image = "https://www.pride.hr/images/thumbs/0001782_a7150-adidas-boxing-gloves-speed-50_1000.jpeg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 19.99m,
                            Price = 9.99m,
                            Title = "Rukavice Adidas 14oz"
                        });
                });

            modelBuilder.Entity("Shop.Shared.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "8oz"
                        },
                        new
                        {
                            Id = 2,
                            Name = "10oz"
                        },
                        new
                        {
                            Id = 3,
                            Name = "12oz"
                        },
                        new
                        {
                            Id = 4,
                            Name = "14oz"
                        },
                        new
                        {
                            Id = 5,
                            Name = "16oz"
                        },
                        new
                        {
                            Id = 6,
                            Name = "XXS"
                        },
                        new
                        {
                            Id = 7,
                            Name = "XS"
                        },
                        new
                        {
                            Id = 8,
                            Name = "S"
                        },
                        new
                        {
                            Id = 9,
                            Name = "M"
                        },
                        new
                        {
                            Id = 10,
                            Name = "L"
                        },
                        new
                        {
                            Id = 11,
                            Name = "XL"
                        },
                        new
                        {
                            Id = 12,
                            Name = "2XL"
                        },
                        new
                        {
                            Id = 13,
                            Name = "3XL"
                        });
                });

            modelBuilder.Entity("ProductSize", b =>
                {
                    b.HasOne("Shop.Shared.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Shared.Size", null)
                        .WithMany()
                        .HasForeignKey("SizesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shop.Shared.Product", b =>
                {
                    b.HasOne("Shop.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
